msaconfig:
  greeting: "test_hello"
  
---

spring:
  profiles: local

msaconfig:
  greeting: "test_welcome to local server"

---

spring:
  profiles: dev

msaconfig:
  greeting: "test_welcome to dev server"

---

spring:
  profiles: test
  
msaconfig:
  greeting: "test_welcome to test server"

---

spring:
  profiles: staging
  
msaconfig:
  greeting: "test_welcome to staging server"

---

spring:
  profiles: prod
  
msaconfig:
  greeting: "test_welcome to prod server!"
